services:
  db:
    image: postgres:latest
    container_name: visualizer-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${SPRING_R2DBC_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_R2DBC_PASSWORD}
    volumes:
      - postgres_db:/var/lib/postgresql/data

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: visualizer-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: r2dbc:postgresql://db:5432/postgres
      DB_USERNAME: ${SPRING_R2DBC_USERNAME}
      DB_PASSWORD: ${SPRING_R2DBC_PASSWORD}
      SPACETRACK_USERNAME: ${SPACETRACK_USERNAME}
      SPACETRACK_PASSWORD: ${SPACETRACK_PASSWORD}


  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: visualizer-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_db:
